Dockerfile:
FROM node:alpine
COPY . /app
CMD node /app/app.js

node.js:
console. log("Name: Vogesh Borhade*)
console.log("Class: TE"):
console. Jog("Subject: LP-II Web Application Development*):
cansole. Jog( "Ass Ignment - 2B"):